'use client';

import { Inter } from "next/font/google";
import "./globals.css";
import { createContext, useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const UserDetailsContext = createContext();

export default function RootLayout({ children }) {

  const [userDetails, setUserDetails] = useState({
    uid: '',
    firstName: '',
    lastName: '',
    email: '',
    photo: '',
    links: []
  });

  useEffect(() => {
    console.log(userDetails);
  }, [userDetails])

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDetailsContext.Provider value={{userDetails, setUserDetails}}>
          {children}
        </UserDetailsContext.Provider>
      </body>
    </html>
  );
}
